name: Set Code Review Status 
# 
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post
on:
  issue_comment:
    types: [created]

jobs:
  pr-reviewed:
    runs-on: ubuntu-latest
    steps:
      - name: Pr reviewed 
        run: echo 'pr reviewed ${{ github.base_ref }}'