name: Set Code Review Status 
# https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post
on:
  issue_comment:
    types: [created]

jobs:
  pr-comment-info:
    runs-on: ubuntu-latest
    steps:
      - name: Comment info 
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "$COMMENT_BODY"
          echo "$ISSUE_TITLE"
